name: Build and push Docker image (simple)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unit testing execution
        shell: bash
        run: |
          echo "UT executing . . ."

      - name: SAST execution
        shell: bash
        run: |
          echo "SonarQube SAST executing . . ."

      - name: Dependencies Analysis
        shell: bash
        run: |
          echo "Snyk Dependencies Analysis executing . . ."

      - name: Versioning & Tagging execution
        shell: bash
        run: |
          echo "Versioning executing . . ."

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat VERSION.txt | tr -d ' \n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kyoimgusers:${{ steps.version.outputs.version }} .

      - name: Image Analysis execution
        shell: bash
        run: |
          echo "Palo Alto Analysis executing . . ."

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kyoimgusers:${{ steps.version.outputs.version }}
